import React, { useState, useRef } from 'react';
import api from '../../services/api';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

const ResumeGenerator = () => {
    const [resumeData, setResumeData] = useState(null);
    const [loading, setLoading] = useState(false);
    const resumeRef = useRef();

    const fetchResume = async () => {
        setLoading(true);
        try {
            // Updated to match your @PostMapping("/generate")
            const { data } = await api.post('/api/resume/generate');
            setResumeData(data);
        } catch (e) {
            console.error("Error generating resume:", e);
        } finally {
            setLoading(false);
        }
    };

    const handleDownloadPDF = async () => {
        const element = resumeRef.current;
        const canvas = await html2canvas(element, { scale: 3, useCORS: true });
        const imgData = canvas.toDataURL('image/png');
        const pdf = new jsPDF('p', 'mm', 'a4');
        const pdfWidth = pdf.internal.pageSize.getWidth();
        const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
        pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
        pdf.save(`${resumeData.name.replace(/\s+/g, '_')}_Resume.pdf`);
    };

    const styles = {
        page: {
            width: '210mm',
            minHeight: '297mm',
            padding: '20mm',
            margin: '20px auto',
            backgroundColor: '#fff',
            color: '#000',
            fontFamily: '"Times New Roman", Times, serif',
            lineHeight: '1.5',
            border: '1px solid #ddd',
            boxShadow: '0 0 10px rgba(0,0,0,0.1)'
        },
        header: { textAlign: 'center', marginBottom: '15px' },
        name: { fontSize: '22pt', fontWeight: 'bold', margin: '0', textTransform: 'uppercase' },
        contact: { fontSize: '10.5pt', margin: '3px 0' },
        sectionTitle: {
            fontSize: '12pt',
            fontWeight: 'bold',
            borderBottom: '1.5px solid #000',
            marginTop: '15px',
            marginBottom: '8px',
            textTransform: 'uppercase'
        },
        link: { color: '#000', textDecoration: 'none', fontWeight: 'bold' },
        content: { fontSize: '11pt', marginBottom: '8px', textAlign: 'justify' },
        list: { paddingLeft: '20px', marginBottom: '10px', fontSize: '11pt' }
    };

    return (
        <div style={{ padding: '20px', backgroundColor: '#f5f5f5', minHeight: '100vh' }}>
            <div style={{ textAlign: 'center', marginBottom: '20px' }}>
                {!resumeData ? (
                    <button className="btn btn-primary" onClick={fetchResume} disabled={loading}>
                        {loading ? 'Processing ML Summary...' : 'Generate Resume'}
                    </button>
                ) : (
                    <button className="btn btn-success" onClick={handleDownloadPDF}>
                        Download PDF
                    </button>
                )}
            </div>

            {resumeData && (
                <div ref={resumeRef} style={styles.page}>
                    {/* Header */}
                    <div style={styles.header}>
                        <h1 style={styles.name}>{resumeData.name}</h1>
                        <p style={styles.contact}>
                            {resumeData.email} | {resumeData.mobile}
                        </p>
                        <div style={styles.contact}>
                            {resumeData.links && resumeData.links.map((link, i) => (
                                <span key={i}>
                                    <a href={link} style={styles.link} target="_blank" rel="noreferrer">
                                        {link.replace(/^https?:\/\//, '')}
                                    </a>
                                    {i < resumeData.links.length - 1 && ' | '}
                                </span>
                            ))}
                        </div>
                    </div>

                    {/* Summary - Generated by ML */}
                    <div style={styles.sectionTitle}>Professional Summary</div>
                    <div style={styles.content}>{resumeData.summary}</div>

                    {/* Education - Structured from Backend */}
                    <div style={styles.sectionTitle}>Education</div>
                    <div style={styles.content}>
                        <strong>{resumeData.education}</strong>
                    </div>

                    {/* Projects - NEW SECTION */}
                    {resumeData.projects && resumeData.projects.length > 0 && (
                        <>
                            <div style={styles.sectionTitle}>Projects</div>
                            <ul style={styles.list}>
                                {resumeData.projects.map((project, i) => (
                                    <li key={i} style={{ marginBottom: '5px' }}>
                                        <strong>{project}</strong>
                                    </li>
                                ))}
                            </ul>
                        </>
                    )}

                    {/* Achievements */}
                    {resumeData.achievements && resumeData.achievements.length > 0 && (
                        <>
                            <div style={styles.sectionTitle}>Achievements</div>
                            <ul style={styles.list}>
                                {resumeData.achievements.map((item, i) => (
                                    <li key={i}>{item}</li>
                                ))}
                            </ul>
                        </>
                    )}

                    <div style={{ marginTop: '30px', borderTop: '1px solid #eee', paddingTop: '10px', textAlign: 'center' }}>
                        <small style={{ color: '#999', fontStyle: 'italic' }}>End of Resume</small>
                    </div>
                </div>
            )}
        </div>
    );
};

export default ResumeGenerator;