spring.application.name=University
server.port = 2008
jwt.secret=c3VwZXJTdHJvbmdKYXd0U2VjcmV0S2V5MTIzNDU2Nzg5MA==
#    =======================
spring.datasource.url=jdbc:mysql://localhost:3306/university
spring.datasource.username=root
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

